#include <TH1D.h>
#include <TH2D.h>
#include <TH3D.h>
#include <RooUnfoldResponse.h>
#include <RooUnfoldBayes.h>
#include <string>

// define the function which performs the unconvoluted 1D unfolding, i.e., 1D unfolding in each pT bin
TH2D* deconvoluted1Dunfolding(TH2D* histoTrainingpTObservableTrue, TH2D* histoTrainingpTObservableSmeared, TH3D* histoTrainingpTObservableSmearedTrue, size_t nIter) {

    // prepare an empty 2D histogram to store the unfolded observable vs pT
    TH2D* histopTObservableUnfoldedC = (TH2D*)histoTrainingpTObservableTrue -> Clone("histopTObservableUnfoldedC_clone2"); // clone the true 2D histogram to acquire its structure
    histopTObservableUnfoldedC -> Reset(); // clear all bin contents and errors, so that we can fill them later
    histopTObservableUnfoldedC -> Sumw2(); // tell the empty histogram to allocate memory for errors
    histopTObservableUnfoldedC -> SetDirectory(nullptr); // memory management


    // extract the number of pT bins
    int nBinspT = histoTrainingpTObservableTrue -> GetXaxis() -> GetNbins();

    // iterate through pT bins, calculate 1D distrivbutions and a response matrix in each one
    for (int iBin = 1; iBin <= nBinspT; iBin++) {

        // project 1D distributions in the i-th bin in the 2D histograms
        std::string nameTrue = "histoObservableTrue_pTBin-" + std::to_string(iBin);
        std::string nameSmeared = "histoObservableSmeared_pTBin-" + std::to_string(iBin);
        TH1D* histoTrainingObservableTrue = histoTrainingpTObservableTrue -> ProjectionY(nameTrue.c_str(), iBin, iBin); // ROOT's ProjectionY doesn't accept the new std::string, but only the const char* type
        TH1D* histoTrainingObservableSmeared = histoTrainingpTObservableSmeared -> ProjectionY(nameSmeared.c_str(), iBin, iBin);

        // extract the RooUnfold-compatible response matrix
        histoTrainingpTObservableSmearedTrue -> GetXaxis() -> SetRange(iBin, iBin); // take only the i-th pT bin
        TH2D* histoTrainingRM = (TH2D*)histoTrainingpTObservableSmearedTrue -> Project3D("zy"); // extract the RM with true (z) on the y-axis and smeared (y) on the x-axis
        std::string nameRM = "histoRM_pTBin-" + std::to_string(iBin);
        histoTrainingRM -> SetName(nameRM.c_str());

        // create the RooUnfold response matrix
        RooUnfoldResponse response(histoTrainingObservableSmeared, histoTrainingObservableTrue, histoTrainingRM);

        // perform the 1D Bayesian unfolding with nIter iterations (set in the 1D Distributions section)
        RooUnfoldBayes unfolded(&response, histoTrainingObservableSmeared, nIter);

        // extract the unfolded histogram
        std::string nameUnfolded = "histoObservableUnfolded_pTBin-" + std::to_string(iBin);
        TH1D* histoObservableUnfolded = (TH1D*)unfolded.Hunfold() -> Clone(nameUnfolded.c_str());
        histoObservableUnfolded -> SetDirectory(nullptr);

        // fill the given pT column in the empty 2D histogram of unfolded observable vs pT
        int nBinsObservable = histoObservableUnfolded -> GetXaxis() -> GetNbins();
        for (int jBin = 1; jBin <= nBinsObservable; jBin++) {

            // extract the bin content and error
            double content = histoObservableUnfolded -> GetBinContent(jBin);
            double error = histoObservableUnfolded -> GetBinError(jBin);

            // fill the empty pT column
            histopTObservableUnfoldedC -> SetBinContent(iBin, jBin, content);
            histopTObservableUnfoldedC -> SetBinError(iBin, jBin, error);
        }

        // memory management -- we delete the pointer generated by ProjectionY, Project3D, and Clone, otherwise RAM would fill up
        delete histoTrainingObservableTrue;
        delete histoTrainingObservableSmeared;
        delete histoTrainingRM;
        delete histoObservableUnfolded;
    }

    // return a pointer to the 2D unfolded histogram
    return histopTObservableUnfoldedC;
}